// This file is automatically generated by vscode-react-native@0.3.1
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/jonathanfunk/Desktop/PROJECTS/Winter App Dev/R10 Project/R10/node_modules/react');
var {Component} = React;

var ReactNative = require('/Users/jonathanfunk/Desktop/PROJECTS/Winter App Dev/R10 Project/R10/node_modules/react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require('/Users/jonathanfunk/Desktop/PROJECTS/Winter App Dev/R10 Project/R10/index.ios.js');

AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('R10', appParameters);
});